<?php
$typeArr[1] = '培训项目';
$typeArr[2] = '培训学员';
$typeArr[56] = '营养早餐系列培训';
$typeArr[78] = '特色“饼”系列';
$typeArr[5] = '关于我们';
$typeArr[80] = '小吃休闲系列';
$typeArr[81] = '铁板系列';
$typeArr[82] = '夜市烧烤系列';
$typeArr[83] = '“汤”系列';
$typeArr[84] = '“粥”系列';
$typeArr[85] = '卤味系列';
$typeArr[86] = '烧烤系列';
$typeArr[87] = '精品凉菜';
$typeArr[45] = '师资团队';
$typeArr[6] = '联系我们';
$typeArr[88] = '精品热菜';
$typeArr[89] = '干锅系列';
$typeArr[90] = '盖饭快餐系列';
$typeArr[91] = '麻辣烫、串串、冒菜系列';
$typeArr[92] = '奶茶系列';
$typeArr[93] = '鲜果茶系列';
$typeArr[94] = '冰激凌系列';
$typeArr[46] = '教学环境';
$typeArr[7] = '餐饮知识';
$typeArr[8] = '学员风采';
$typeArr[10] = '心得感悟';
$typeArr[11] = '荣誉资质';
$typeArr[12] = '新闻动态';
$typeArr[13] = '常见问答';
$typeArr[14] = '陕西面食系列培训';
$typeArr[75] = '特色“饼”系列';
$typeArr[71] = '肉夹馍系列';
$typeArr[50] = '汤品粥类系列培训';
$typeArr[76] = '包子、饺子系列';
$typeArr[77] = '营养早餐系列';
$typeArr[49] = '卤味烧烤系列培训';
$typeArr[24] = '网站地图';
$typeArr[25] = '全站幻灯';
$typeArr[70] = '凉皮系列';
$typeArr[27] = '饮品培训';
$typeArr[72] = '泡馍系列';
$typeArr[73] = '粉线、砂锅系列';
$typeArr[54] = '陕西小吃培训项目';
$typeArr[74] = '各类面食系列';
$typeArr[52] = '川味特色系列培训';
$typeArr[47] = '教学服务';
$typeArr[51] = '街边休闲小吃培训';
$typeArr[79] = '街边煎炸系列';
$typeArr[69] = '行业新闻';
$typeArr[95] = '手机站跳转';
?>