
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:beizhu itemname="留言" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:beizhu>

<field:lxdz itemname="联系地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxdz>
