<li><a href="[field:arcurl/]" class="tu">
                <img src="[field:litpic/]" alt=""></a>
                <div class="wen">
                    <a href="[field:arcurl/]" class="num01" title="#">[field:title/]</a>
                    <a href="[field:arcurl/]" class="left">
                        <img src="/sink/images/left.png" alt=""></a></div>
                <div class="line"></div>
            </li>

            <li><a href="" class="tu"><img src="images/pro01.jpg" alt=""></a>
                <div class="wen"><a href="" class="num01" title="#">产品名称</a><a href="" class="left"><img
                        src="images/left.png" alt=""></a></div>
                <div class="line"></div>
            </li>