<a href="view.php?aid=[field:id /]">
                    <div class="mediabox" id="box1">

                        <dt><img src="/m_images/imga_r1.jpg" alt="img01" /></dt>
                        <dd> <h3 style="color:#000;">[field:title/]</h3>
                            <p>[field:body function="cn_substr(@me,60)" /]</p>
                        </dd>

                    </div>
                </a>