<h4><a href="{dede:field name="typeurl"/}" title="{dede:field name="typename"/}" target="_blank">{dede:field name="typename"/}</a></h4>
      <div class="b4">
        <ul>
          {dede:channel type="son"}
          <li><a href="[field:typeurl/]" title="[field:typename/]" target="_blank">[field:typename/]</a></li>
          {/dede:channel}
        </ul>
        <div class="clear"></div>
      </div>