<?php
$z[0]=Array("field","",429,448);
$z[0][4]['name']="title";
$z[1]=Array("global","",449,475);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",946,985);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1227,1249);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1396,1415);
$z[4][4]['name']="title";
$z[5]=Array("field","",1441,1497);
$z[5][4]['name']="pubdate";
$z[5][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[6]=Array("field","",1618,1636);
$z[6][4]['name']="body";
$z[7]=Array("include","",1796,1835);
$z[7][4]['filename']="footer_m.htm";

?>