<?php
$z[0]=Array("field","",428,447);
$z[0][4]['name']="title";
$z[1]=Array("global","",448,474);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",945,984);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1226,1248);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1395,1414);
$z[4][4]['name']="title";
$z[5]=Array("field","",1440,1496);
$z[5][4]['name']="pubdate";
$z[5][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[6]=Array("field","",1617,1635);
$z[6][4]['name']="body";
$z[7]=Array("arclist","\n\n                                <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\n\n                                    <img src=\"[field:litpic/]\" title=\"[field:title/]\"  />\n\n                                    [field:title/]</a>\n",2035,2358);
$z[7][4]['typeid']="3";
$z[7][4]['flag']="p";
$z[7][4]['row']="3";
$z[7][4]['titlelen']="60";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("arclist","\n                    <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">[field:title/]</a>\n",2769,2942);
$z[8][4]['typeid']="11";
$z[8][4]['row']="5";
$z[8][4]['titlelen']="60";
$z[8][4]['orderby']="pubdate";
$z[9]=Array("include","",3034,3073);
$z[9][4]['filename']="footer_m.htm";

?>