<div class="item">



  <div class="cell">



    <div class="pic"> <img src="[field:litpic/]" alt="[field:title/]">



      <p class="name">[field:title/]</p>



    </div>



    <div class="txt">



<!--      <p>[field:info/]... </p>-->



      <div class="num">报名人气：[field:click/]</div>



    </div>



  </div>



  <div class="btn"> <a href="[field:arcurl/]" class="xq" title="专业详情"><span>专业详情</span></a> <a href="tencent://message/?uin=[field:global.qq/]&Menu=yes" class="zx" title="在线咨询"><span>在线咨询</span></a> </div>



</div>