<li><a href="" class="tu"><img src="/sink/images/pro01.jpg" alt=""></a><a href="/case/99687.html"
                                                                                      class="wen">成功案例名称</a></li>

            <!-- 表单 -->
            <li class="case-form">
                <ol>
                    <dl><img src="/sink/images/f-icon01.jpg" alt=""><input type="text" class="name" value="请输入您的姓名"/>
                    </dl>
                    <dl><img src="/sink/images/f-icon02.jpg" alt=""><input type="text" class="name" value='请输入您的电话'/>
                    </dl>
                    <dl><img src="/sink/images/f-icon03.jpg" alt=""><input type="text" class="name" value='请输入您的邮箱'/>
                    </dl>
                    <input type="submit" class="submit" value="提交"/>
                </ol>
                <script src="js/n/message.js"></script>
            </li>
        </ul>
    </div>
</div>
<!-- about -->
<div class="about-box">
    <div class="about-center">
        <h3>陕西鲁明热力设备工程有限公司</h3>
        <p>
            陕西鲁明热力设备工程有限公司公司简介陕西鲁明热力设备工程有限公司公司简介陕西鲁明热力设备工程有限公司公司简介陕西鲁明热力设备工程有限公司公司简介陕西鲁明热力设备工程有限公司公司简介陕西鲁明司简介陕西鲁明热力设备工程有限公司公司简介陕西鲁明热力设备工程有限公司公司简介陕西鲁明热力设备工程有限公司公司简介陕西鲁明热力设备工程有限公司公司简介</p>
        <a href="" title="">more+</a>
        <!-- 展示 -->
        <div class="zhanshi-box">
            <div class="zhanzhi-tit">
                <span>公司展示</span><a href="" title="#">more+</a>
            </div>
            <ul>
                <li><a href="" class="tu"><img src="/sink/images/pro01.jpg" alt=""></a><a href="" class="wen">厂房展示</a>
                </li>
                <li><a href="" class="tu"><img src="/sink/images/pro01.jpg" alt=""></a><a href="" class="wen">厂房展示</a>
                </li>
                <li><a href="" class="tu"><img src="/sink/images/pro01.jpg" alt=""></a><a href="" class="wen">厂房展示</a>
                </li>
                <li><a href="" class="tu"><img src="/sink/images/pro01.jpg" alt=""></a><a href="" class="wen">厂房展示</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- hero -->
<div class="hero-box">
    <div class="hero-center">
        <div class="c-tit">
            <div class="line"></div>
            <h3>鲁明热力 · <i>荣誉资质</i></h3>
        </div>
        <div id="marquee1" class="marqueeleft">
            <div class="cjfm-cen">
                <ul>
                    <li><a class="pic" href="" title="#"><img src="/sink/images/hero01.jpg"></a>
                        <a class="pic01" href="" title="#">荣誉资质</a>
                    </li>
                    <li><a class="pic" href="" title="#"><img src="/sink/images/hero01.jpg"></a>
                        <a class="pic01" href="" title="#">荣誉资质</a>
                    </li>
                    <li><a class="pic" href="" title="#"><img src="/sink/images/hero01.jpg"></a>
                        <a class="pic01" href="" title="#">荣誉资质</a>
                    </li>
                    <li><a class="pic" href="" title="#"><img src="/sink/images/hero01.jpg"></a>
                        <a class="pic01" href="" title="#">荣誉资质</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- news -->
<div class="news-box">
    <div class="news-center">
        <h3 data-scroll-reveal="enter left and move 100px over 1.3s">鲁明热力 · <i>新闻资讯</i></h3>
        <ul class="title" data-scroll-reveal="enter bottom and move 100px over 1.5s">
            <li class="n-active">公司动态</li>
            <li>行业动态</li>
            <li>常见问题</li>
        </ul>
        <div class="center" data-scroll-reveal="enter bottom and move 100px over 1.7s">
            <ul>
                <li class="top">
                    <div class="left">
                        <a href="#" class="tu">
                            <img src="/sink/images/hero01.jpg" alt=""></a><a href="#" class="wen">测试资料--陕西鲁明热力设备工程有限公司喜获
                        瑞行集团长安区新区热力?</a>

                    </div>
                    <div class="right">
                        <dl><a href="#" class="tu"><img src="/sink/images/pro01.jpg"></a><a href="#" class="wen">测试资料--陕西鲁明热力设备工程有限公司喜获
                            瑞行集团长安区新区热力</a>
                            <p>测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</p>
                            <div class="time"><span>2019-01-30</span></div>
                        </dl>
                        <dl><a href="#" class="tu"><img src="/sink/images/pro01.jpg"></a><a href="#" class="wen">测试资料--如何将网站的效果发挥到更好？</a>
                            <p>测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</p>
                            <div class="time"><span>2019-01-30</span></div>
                        </dl>

                    </div>
                </li>
                <li class="bottom">
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                </li>
            </ul>
            <ul>
                <li class="top">
                    <div class="left">
                        <a href="#" class="tu">
                            <img src="/sink/images/pro01.jpg" alt=""></a><a href="#" class="wen">测试资料--陕西鲁明热力设备工程有限公司喜获
                        瑞行集团长安区新区热力?</a>

                    </div>
                    <div class="right">
                        <dl><a href="#" class="tu"><img src="/sink/images/pro01.jpg"></a><a href="#" class="wen">测试资料--陕西鲁明热力设备工程有限公司喜获
                            瑞行集团长安区新区热力</a>
                            <p>测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</p>
                            <div class="time"><span>2019-01-30</span></div>
                        </dl>
                        <dl><a href="#" class="tu"><img src="/sink/images/pro01.jpg"></a><a href="#" class="wen">测试资料--如何将网站的效果发挥到更好？</a>
                            <p>测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</p>
                            <div class="time"><span>2019-01-30</span></div>
                        </dl>

                    </div>
                </li>
                <li class="bottom">
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                </li>
            </ul>
            <ul>
                <li class="top">
                    <div class="left">
                        <a href="#" class="tu">
                            <img src="/sink/images/pro01.jpg" alt=""></a><a href="#" class="wen">测试资料--陕西鲁明热力设备工程有限公司喜获
                        瑞行集团长安区新区热力?</a>

                    </div>
                    <div class="right">
                        <dl><a href="#" class="tu"><img src="/sink/images/pro01.jpg"></a><a href="#" class="wen">测试资料--陕西鲁明热力设备工程有限公司喜获
                            瑞行集团长安区新区热力</a>
                            <p>测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</p>
                            <div class="time"><span>2019-01-30</span></div>
                        </dl>
                        <dl><a href="#" class="tu"><img src="/sink/images/pro01.jpg"></a><a href="#" class="wen">测试资料--如何将网站的效果发挥到更好？</a>
                            <p>测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</p>
                            <div class="time"><span>2019-01-30</span></div>
                        </dl>

                    </div>
                </li>
                <li class="bottom">
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                    <dl><a href="#" title="">测试资料--陕西鲁明热力设备工程有限公司喜获 瑞行集团长安区新区热力</a>
                        <p>01-30</p></dl>
                </li>
            </ul>
        </div>
    </div>
</div>


<!-- js -->
<script src="/sink/js/jquery.min.js"></script>
<script src="/sink/js/jquery.SuperSlide.2.1.1.js"></script>
<!--[if !IE]><!-->
<script src="/sink/js/scrollReveal.js"></script>
<!--<![endif]-->
<script src="/sink/js/index.js"></script>


{dede:include filename="footer.htm"