<li><a href="[field:arcurl/]" class="tu">
                <img src="[field:litpic/]" alt=""></a>
                <div class="wen">
                    <a href="[field:arcurl/]" class="num01" title="#">[field:title/]</a>
                    <a href="[field:arcurl/]" class="left">
                        <img src="/sink/images/left.png" alt=""></a></div>
                <div class="line"></div>
            </li>