<?php
$z[0]=Array("field","",429,448);
$z[0][4]['name']="title";
$z[1]=Array("global","",449,475);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",778,817);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1059,1081);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1165,1186);
$z[4][4]['name']="content";
$z[5]=Array("include","",1314,1353);
$z[5][4]['filename']="footer_m.htm";

?>