<?php
$z[0]=Array("field","",251,280);
$z[0][4]['name']="typename";
$z[1]=Array("global","",281,307);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",347,376);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",415,473);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",958,996);
$z[4][4]['filename']="header.htm";
$z[5]=Array("arclist","-->\n    <!--<li><a href=\"javascript:void(0);\"> <img src=\"[field:litpic/]\" /></a></li>-->\n    <!--",1057,1205);
$z[5][4]['typeid']="25";
$z[5][4]['row']="5";
$z[6]=Array("include","",1328,1366);
$z[6][4]['filename']="sousuo.htm";
$z[7]=Array("include","",1983,2019);
$z[7][4]['filename']="left.htm";
$z[8]=Array("field","",2092,2121);
$z[8][4]['name']="position";
$z[9]=Array("field","",2167,2185);
$z[9][4]['name']="body";
$z[10]=Array("field","",2189,2210);
$z[10][4]['name']="content";
$z[11]=Array("likeart","\n          <dd>\n            <div class=\"img\"> <a href=\"[field:arcurl /]\"> <img src=\"[field:litpic/]\" /></a></div>\n            <div class=\"txt\"> <a href=\"[field:arcurl /]\"> [field:title/]</a></div>\n          </dd>\n          ",2347,2621);
$z[11][4]['titlelen']="30";
$z[11][4]['row']="4";
$z[12]=Array("include","",2725,2762);
$z[12][4]['filename']="footer.htm";

?>