<?php
$z[0]=Array("global","",1471,1503);
$z[0][4]['name']="activepath";
$z[1]=Array("global","",1779,1834);
$z[1][4]['name']="backurl";
$z[1][4]['function']="urlencode(@me)";
$z[2]=Array("global","",2393,2425);
$z[2][4]['name']="activepath";
$z[3]=Array("global","",2646,2676);
$z[3][4]['name']="filename";
$z[4]=Array("global","",2805,2838);
$z[4][4]['name']="contentView";
$z[5]=Array("global","",3483,3514);
$z[5][4]['name']="extension";

?>