<?php
$z[0]=Array("arclist","\n        <li class=\"li\">\n\n            <div class=\"bcjcpzxs\"><a href=\"view.php?aid=[field:id/]\"><img src=\"[field:litpic/]\"></a>\n                <p>[field:title/]</p></div>\n\n            <div class=\"bcjcpzxx\"><a href=\"view.php?aid=[field:id/]\" class=\"a1\">了解详情</a><a href=\"mqqwpa://im/chat?chat_type=wpa&uin=200835900&version=1&src_type=web&web_src=oicqzone.com\" class=\"a2\">立即咨询</a>\n            </div>\n\n        </li>\n\n        ",3058,3585);
$z[0][4]['typeid']="3";
$z[0][4]['row']="6";
$z[0][4]['titlelen']="30";
$z[0][4]['infolen']="120";
$z[0][4]['isweight']="Y";
$z[1]=Array("arclist","\n        <li class=\"li\">\n\n            <div class=\"bcjcpzxs\"><a href=\"view.php?aid=[field:id/]\"><img src=\"[field:litpic/]\"></a>\n                <p>[field:title/]</p></div>\n\n\n        </li>\n\n        ",3990,4275);
$z[1][4]['typeid']="5";
$z[1][4]['row']="6";
$z[1][4]['titlelen']="30";
$z[1][4]['infolen']="120";
$z[1][4]['isweight']="Y";
$z[2]=Array("sql","\n        　　[field:content function=\"cn_substr(@me,336)\"/]\n        ",4596,4737);
$z[2][4]['sql']="Select content from dede_arctype where id=1";
$z[3]=Array("arclist","\n        <li><a href=\"view.php?aid=[field:id/]\">\n            <p>[field:title/]</p>\n            <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></a>\n        </li>\n        ",4993,5264);
$z[3][4]['typeid']="6";
$z[3][4]['row']="6";
$z[3][4]['titlelen']="30";
$z[3][4]['infolen']="120";
$z[3][4]['isweight']="Y";

?>