<?php
$z[0]=Array("include","",0,40);
$z[0][4]['filename']="header_m.htm";
$z[1]=Array("arclist","\n\n\n<div class=\"na_b teacher\"><a href=\"view.php?aid=[field:id /]\" class=\"tu\"><img src=\"[field:picname/]\"/></a><a href=\"\" class=\"wen\">[field:title/]</a></div>\n\n",3802,4023);
$z[1][4]['typeid']="45";
$z[1][4]['titlelen']="60";
$z[1][4]['row']="8";
$z[2]=Array("arclist","\n        <a href=\"view.php?aid=[field:id /]\"><div class=\"slide\"><img style=\"width: 125px;\" src=\"[field:picname/]\"></div></a>\n        ",4888,5084);
$z[2][4]['typeid']="11";
$z[2][4]['titlelen']="60";
$z[2][4]['row']="8";
$z[3]=Array("arclist","\n                <a href=\"view.php?aid=[field:id /]\">\n                    <div class=\"mediabox\" id=\"box1\">\n\n                        <dt><img src=\"/m_images/imga_r1.jpg\" alt=\"img01\" /></dt>\n                        <dd> <h3 style=\"color:#000;\">[field:title/]</h3>\n                            <p>[field:body function=\"cn_substr(@me,60)\" /]</p>\n                        </dd>\n\n                    </div>\n                </a>\n                ",7790,8320);
$z[3][4]['typeid']="12";
$z[3][4]['titlelen']="60";
$z[3][4]['row']="4";
$z[3][4]['addfields']="body";
$z[3][4]['channelid']="1";
$z[4]=Array("arclist","\n                <a href=\"view.php?aid=[field:id /]\">\n                    <div class=\"mediabox\" id=\"box1\">\n\n                        <dt><img src=\"/m_images/imga_r1.jpg\" alt=\"img01\" /></dt>\n                        <dd> <h3 style=\"color:#000;\">[field:title/]</h3>\n                            <p>[field:body function=\"cn_substr(@me,60)\" /]</p>\n                        </dd>\n\n                    </div>\n                </a>\n                ",8397,8927);
$z[4][4]['typeid']="69";
$z[4][4]['titlelen']="60";
$z[4][4]['row']="4";
$z[4][4]['addfields']="body";
$z[4][4]['channelid']="1";
$z[5]=Array("arclist","\n                <a href=\"view.php?aid=[field:id /]\">\n                    <div class=\"mediabox\" id=\"box1\">\n\n                        <dt><img src=\"/m_images/imga_r1.jpg\" alt=\"img01\" /></dt>\n                        <dd> <h3 style=\"color:#000;\">[field:title/]</h3>\n                            <p>[field:body function=\"cn_substr(@me,60)\" /]</p>\n                        </dd>\n\n                    </div>\n                </a>\n                ",9004,9534);
$z[5][4]['typeid']="13";
$z[5][4]['titlelen']="60";
$z[5][4]['row']="4";
$z[5][4]['addfields']="body";
$z[5][4]['channelid']="1";
$z[6]=Array("include","",10415,10454);
$z[6][4]['filename']="footer_m.htm";

?>