<?php
$z[0]=Array("include","",0,39);
$z[0][4]['filename']="header_m.htm";
$z[1]=Array("field","",221,243);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\n<div class=\"bei2 peixun peixun-page\"><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></div>\n",266,427);
$z[2][4]['typeid']="1";
$z[2][4]['row']="100";
$z[2][4]['type']="son";
$z[3]=Array("include","",430,469);
$z[3][4]['filename']="footer_m.htm";

?>