<?php
$z[0]=Array("include","",0,39);
$z[0][4]['filename']="header_m.htm";
$z[1]=Array("field","",112,134);
$z[1][4]['name']="typename";
$z[2]=Array("field","",182,204);
$z[2][4]['name']="typename";
$z[3]=Array("list","    <a href=\"view.php?aid=[field:id/]\">        <div class=\"bei2\">        <img src=\"[field:litpic/]\" />        <h4>[field:title/]</h4>        <p>  [field:description function=\"cn_substr(@me,80)\" /]...</p>        <div class=\"butbt\"><a href=\"view.php?aid=[field:id/]\">查看详情</a></div>    </div>    </a>    ",275,623);
$z[3][4]['pagesize']="9999";
$z[4]=Array("include","",629,668);
$z[4][4]['filename']="footer_m.htm";

?>