<?php
$z[0]=Array("field","",429,448);
$z[0][4]['name']="title";
$z[1]=Array("global","",449,475);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",748,787);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",986,1008);
$z[3][4]['name']="typename";
$z[4]=Array("list","\n\n	  <a href=\"view.php?aid=[field:id/]\" class=\"s-babg\">\n      <dl class=\"prolistbgfa\">\n        <dt><img src=\"[field:litpic/]\" width=\"130\" height=\"119\" /></dt>\n        <h3 class=\"s-wc\">[field:title/]</h3>\n        <p>[field:description function=\"cn_substr(@me,200)\" /]...</p>\n        <span></span>\n        <div class=\"clear\"></div>\n      </dl>\n      </a>\n\n",1066,1456);
$z[4][4]['pagesize']="5";
$z[5]=Array("pagelist","",1542,1620);
$z[5][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1641,1680);
$z[6][4]['filename']="footer_m.htm";

?>