<?php
$z[0]=Array("include","",0,39);
$z[0][4]['filename']="header_m.htm";
$z[1]=Array("field","",112,134);
$z[1][4]['name']="typename";
$z[2]=Array("field","",182,204);
$z[2][4]['name']="typename";
$z[3]=Array("channel","<a href=\"list.php?tid=[field:id/]\"><div class=\"peixun_1b\">    <h1>[field:typename/]</h1>    <div class=\"bei1\"><img src=\"[field:typeimg /]\" /></div>    <h1>[field:seotitle/]</h1>    <p>[field:content/]</p>    <div class=\"butbt\"><a href=\"list.php?tid=[field:id/]\">点击更多</a></div></div></a>",217,552);
$z[3][4]['type']="son";
$z[4]=Array("include","",552,591);
$z[4][4]['filename']="footer_m.htm";

?>