<?php
$z[0]=Array("include","",0,39);
$z[0][4]['filename']="header_m.htm";
$z[1]=Array("field","",472,494);
$z[1][4]['name']="typename";
$z[2]=Array("list","	  <a href=\"view.php?aid=[field:id/]\" class=\"s-babg\">      <dl class=\"prolistbgfa\">        <dt><img src=\"[field:litpic/]\" width=\"130\" height=\"119\" /></dt>        <h3 class=\"s-wc\">[field:title/]77777</h3>        <p>[field:description function=\"cn_substr(@me,200)\" /]...</p>        <span></span>        <div class=\"clear\"></div>      </dl>      </a>",547,930);
$z[2][4]['pagesize']="5";
$z[3]=Array("pagelist","",1011,1089);
$z[3][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[3][4]['listsize']="5";
$z[4]=Array("include","",1102,1141);
$z[4][4]['filename']="footer_m.htm";

?>