<?php
$z[0]=Array("field","",251,280);
$z[0][4]['name']="typename";
$z[1]=Array("global","",281,307);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",353,380);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",427,457);
$z[3][4]['name']="cfg_description";
$z[4]=Array("include","",930,968);
$z[4][4]['filename']="header.htm";
$z[5]=Array("arclist","-->\n    <!--<li><a href=\"javascript:void(0);\"> <img src=\"[field:litpic/]\" /></a></li>-->\n    <!--",1029,1177);
$z[5][4]['typeid']="25";
$z[5][4]['row']="5";
$z[6]=Array("include","",1300,1338);
$z[6][4]['filename']="sousuo.htm";
$z[7]=Array("include","",1955,1991);
$z[7][4]['filename']="left.htm";
$z[8]=Array("field","",2064,2093);
$z[8][4]['name']="position";
$z[9]=Array("list","\n          <dd>\n            <div class=\"img\"> <a href=\"[field:arcurl/]\"> <img src=\"[field:litpic/]\" /> </a></div>\n            <div class=\"txt\"> <a href=\"[field:arcurl/]\"> [field:title/]</a></div>\n          </dd>\n          <span style=\"display: none;\"> </span> ",2154,2466);
$z[9][4]['pagesize']="12";
$z[9][4]['titlelen']="50";
$z[10]=Array("pagelist","",2521,2592);
$z[10][4]['listitem']="info,index,end,pre,next,pageno";
$z[10][4]['listsize']="1";
$z[11]=Array("likeart","\n          <dd>\n            <div class=\"img\"> <a href=\"[field:arcurl /]\"> <img src=\"[field:litpic/]\" /></a></div>\n            <div class=\"txt\"> <a href=\"[field:arcurl /]\"> [field:title/]</a></div>\n          </dd>\n          ",2718,2992);
$z[11][4]['titlelen']="30";
$z[11][4]['row']="4";
$z[12]=Array("include","",3095,3132);
$z[12][4]['filename']="footer.htm";

?>