<?php
$z[0]=Array("include","",0,39);
$z[0][4]['filename']="header_m.htm";
$z[1]=Array("field","",112,134);
$z[1][4]['name']="typename";
$z[2]=Array("list","<a href=\"view.php?aid=[field:id/]\"><div class=\"bei2\"><img src=\"[field:litpic/]\" /><h2>[field:title/]</h2><h3>[field:description function=\"cn_substr(@me,60)\" /]...</h3></div></a>",232,432);
$z[3]=Array("include","",432,471);
$z[3][4]['filename']="footer_m.htm";

?>