<?php
$z[0]=Array("field","",251,280);
$z[0][4]['name']="typename";
$z[1]=Array("global","",281,307);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",347,376);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",415,473);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",944,982);
$z[4][4]['filename']="header.htm";
$z[5]=Array("arclist","-->\n    <!--<li><a href=\"javascript:void(0);\"> <img src=\"[field:litpic/]\" /></a></li>-->\n    <!--",1043,1191);
$z[5][4]['typeid']="25";
$z[5][4]['row']="5";
$z[6]=Array("include","",1314,1352);
$z[6][4]['filename']="sousuo.htm";
$z[7]=Array("include","",1969,2005);
$z[7][4]['filename']="left.htm";
$z[8]=Array("field","",2078,2107);
$z[8][4]['name']="position";
$z[9]=Array("list","\n          <dd>\n            <div class=\"img\"> <a href=\"[field:arcurl/]\"> <img src=\"[field:litpic/]\" /> </a></div>\n            <div class=\"txt\"> <a href=\"[field:arcurl/]\"> [field:title/]</a></div>\n          </dd>\n          <span style=\"display: none;\"> </span> ",2168,2480);
$z[9][4]['pagesize']="12";
$z[9][4]['titlelen']="50";
$z[10]=Array("pagelist","",2535,2606);
$z[10][4]['listitem']="info,index,end,pre,next,pageno";
$z[10][4]['listsize']="1";
$z[11]=Array("likeart","\n          <dd>\n            <div class=\"img\"> <a href=\"[field:arcurl /]\"> <img src=\"[field:litpic/]\" /></a></div>\n            <div class=\"txt\"> <a href=\"[field:arcurl /]\"> [field:title/]</a></div>\n          </dd>\n          ",2732,3006);
$z[11][4]['titlelen']="30";
$z[11][4]['row']="4";
$z[12]=Array("include","",3109,3146);
$z[12][4]['filename']="footer.htm";

?>