<?php
$z[0]=Array("global","",234,262);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",274,293);
$z[1][4]['name']="title";
$z[2]=Array("global","",294,320);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",360,389);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",428,486);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",1552,1589);
$z[5][4]['filename']="header.htm";
$z[6]=Array("channelartlist","\n      <h4><a href=\"{dede:field name=\"typeurl\"/}\" title=\"{dede:field name=\"typename\"/}\" target=\"_blank\">{dede:field name=\"typename\"/}</a></h4>\n      <div class=\"b4\">\n        <ul>\n          {dede:channel type=\"son\"}\n          <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" target=\"_blank\">[field:typename/]</a></li>\n          {/dede:channel}\n        </ul>\n        <div class=\"clear\"></div>\n      </div>\n      ",2124,2598);
$z[6][4]['typeid']="top";
$z[7]=Array("include","",2649,2686);
$z[7][4]['filename']="footer.htm";

?>