<?php
$z[0]=Array("global","",78,106);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("wintitle","",118,134);
$z[2]=Array("global","",190,224);
$z[2][4]['name']="cfg_plus_dir";
$z[3]=Array("global","",270,304);
$z[3][4]['name']="cfg_plus_dir";
$z[4]=Array("global","",525,559);
$z[4][4]['name']="cfg_plus_dir";
$z[5]=Array("wecome_info","",590,609);
$z[6]=Array("winform","",724,739);
$z[7]=Array("lang_cms_powerby","",796,820);

?>