<?php  exit();
/*
Page: /favicon.ico
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:23:44
*/
?>
<?php  exit();
/*
Page: /dede
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:23:51
*/
?>
<?php  exit();
/*
Page: /member/ajax_loginsta.php
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:23:55
*/
?>
<?php  exit();
/*
Page: /favicon.ico
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:23:59
*/
?>
<?php  exit();
/*
Page: /favicon.ico
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:24:08
*/
?>
<?php  exit();
/*
Page: /favicon.ico
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:24:13
*/
?>
<?php  exit();
/*
Page: /favicon.ico
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:24:24
*/
?>
<?php  exit();
/*
Page: /favicon.ico
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:24:25
*/
?>
<?php  exit();
/*
Page: /favicon.ico
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:24:28
*/
?>
<?php  exit();
/*
Page: /cms/images/shortcut-button-bg.gif
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:24:30
*/
?>
<?php  exit();
/*
Page: /favicon.ico
Error: Unknown column 'typeimg' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath,typeimg
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 10 </font>
Time2018-11-05 15:24:30
*/
?>
<?php  exit();
/*
Page: /updatehome.php
Error: 无法使用数据库
Time2019-01-22 18:01:08
*/
?>
<?php  exit();
/*
Page: /zdwl/login.php
Error: 无法使用数据库
Time2019-01-22 18:02:24
*/
?>
<?php  exit();
/*
Page: /zdwl/login.php
Error: 无法使用数据库
Time2019-01-22 18:02:45
*/
?>
<?php  exit();
/*
Page: /updatehome.php
Error: 无法使用数据库
Time2019-01-22 18:03:50
*/
?>
<?php  exit();
/*
Page: /updatehome.php
Error: No database selected <br />Error sql: <font color='red'>Select * From `dede_homepageset` LIMIT 0,1;</font>
Time2019-01-22 18:03:50
*/
?>
<?php  exit();
/*
Page: /zdwl/login.php
Error: 无法使用数据库
Time2019-01-22 18:04:18
*/
?>
<?php  exit();
/*
Page: /zdwl/login.php
Error: No database selected <br />Error sql: <font color='red'>SELECT admin.*,atype.purviews FROM `dede_admin` admin LEFT JOIN `dede_admintype` atype ON atype.rank=admin.usertype WHERE admin.userid LIKE 'admin' LIMIT 0,1</font>
Time2019-01-22 18:04:18
*/
?>
